CREATE TABLE [dbo].[Haikus]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Text] NVARCHAR(MAX) NOT NULL,
	[UserId] BIGINT NOT NULL,
	[Date] DATETIME NOT NULL ,
    [IsDeleted] BIT NOT NULL DEFAULT 0, 
    [RatingValue] BIGINT NOT NULL DEFAULT 0, 
    [RatersCount] BIGINT NOT NULL DEFAULT 0, 
    CONSTRAINT [FK_Haikus_Users] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id])
)
