CREATE TABLE [dbo].[Users]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Username] NVARCHAR(50) NOT NULL,
	[PublishCode] NVARCHAR(MAX) NOT NULL,
	[IsDeleted] BIT DEFAULT 0 NOT NULL, 
    [IsVip] BIT NOT NULL DEFAULT 0, 
    [RatingValue] BIGINT NOT NULL DEFAULT 0, 
    [RatersCount] BIGINT NOT NULL DEFAULT 0
)
